### PR TITLE
Remediation for birthYear, deathYear, and roles response serialization

### LINKED ISSUE #166: Incorrect Actor and Movie Id Validation
## Description
Run of webvalidate revealed that the digits for the IDs (e.g., '00000' of 'nm00000') are not validate correctly for 0 value.  Additionally, given that it didn't fail validation it returned a 404 since the record could not be found.

## Expected Behavior
- Should invalidate such an ID
- Should return a 400 for bad request.

## Reproduce
1. Run Helium Java locally
2. In bash window execute: curl -v http://localhost:8080/api/actors/nm000000
3. See response

## Additional Context
- _(If applicable: Add any other context about the problem here; for example: doc changes, screenshots, logs, links, etc)_

### LINKED ISSUE #167: deathYear included in output as 0
## Description
- When an Actor is retrieved that does have a deathYear value set the API is returning the default value for deathYear which is 0.

## Expected Behavior
- When an Actor does not have a deathYear then the element should not be in the response JSON.

## Reproduce
1. Run Helium Java locally
2. Execute: curl -v http://localhost:8080/api/actors/nm0000123
3. Review results and see deathYear is present with the value of 0

### LINKED ISSUE #168: Roles has null value
## Description
- Issuing a query for movies by actors results in Role entities with null values.  
  * Issuing:  http http://localhost:8080/api/movies?actorid=nm0000206
  * Contains results such as:
            {
                "actorId": "nm0267512", 
                "birthYear": 1958, 
                "category": "Director", 
                "characters": null, 
                "name": "Valerie Faris", 
                "order": 6
            }, 
## Expected Behavior
- If no roles are assigned then the element should not be present.

## Reproduce
1. Run Helium Java locally
2. Execute  http http://localhost:8080/api/movies?actorid=nm0000206
3. Review results

### PR DESCRIPTION
**Pull request by jofultz**
## Type of PR

- [ ] Documentation changes
- [X] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## Purpose of PR
Updates to code base to correct issues serializing birthYear, deathYear, and roles when they were not in the source data.

## Issues Closed or Referenced

- Closes #166 
- Closes #167 
- Closes #168

### CODE REVIEW

File: src/main/java/com/microsoft/cse/helium/app/utils/ParameterValidator.java [hunk 1]
```diff
@@ -1,32 +1,64 @@
...
+    if (id == null 
+        || id.isEmpty() 
+        || id.length() < 7 
+        || id.length() > 11 
+        || !id.substring(0, 2).equals(prefixToMatch) 
+        || !isInteger(id.substring(2))) {
+      retValue = false;
+    } else {
+      // No out params, so checking value of digits in id 
+      if (Integer.parseInt(id.substring(2)) <= 0) {
```
Comment (bartr) [inline src/main/java/com/microsoft/cse/helium/app/utils/ParameterValidator.java:55]: can you put this as the last || in the first check? it won't get called if it's not an int (will it?)

Comment (jofultz) [reply src/main/java/com/microsoft/cse/helium/app/utils/ParameterValidator.java]: I wasn't sure of the short-circuit logic for Java at the time.  I've checked it and modified it as you suggested.
